checkpoint:
  paths:
  - /home/mplata/repos/aad-plus-plus/adversarial_attacks_generator/trained_models/aad__frontend_lcnn_fold_-1__1665614383.7074096/ckpt.pth
data:
  adversarial_attacks:
  - PGDL2
  - PGDL2_eps15
  - PGDL2_eps20
  cnn_features_setting:
    frontend_algorithm: []
    use_spectrogram: false
  seed: 42
model:
  name: frontend_lcnn
  optimizer:
    lr: 1.0e-05
  parameters:
    frontend_algorithm:
    - lfcc
    input_channels: 1
