data:
  seed: 42
  adversarial_attacks: ["FGSM"]

checkpoint:
  paths: [
    
  ]

model:
  name: "lcnn"
  parameters:
    frontend_algorithm: ["lfcc"]
    input_channels: 1
  optimizer:
    lr: 0.0001
