data:
  seed: 42
  cnn_features_setting:
    frontend_algorithm: []  # ["mfcc"] or ["lfcc"] or ["mfcc", "lfcc"] or []
    use_spectrogram: False
  adversarial_attacks: ["FGSM"]

checkpoint:
  paths: [
    "../trained_models/aad__frontend_lcnn_fold_-1__1665325273.8663843/ckpt.pth"
  ]

model:
  name: "lcnn"
  parameters:
    frontend_algorithm: ["lfcc"]
    input_channels: 1
  optimizer:
    lr: 0.0001
