data:
  seed: 42

checkpoint:
  paths: [
    # "../trained_models/aad__rawnet3_fold_-1__1665387053.21383/ckpt.pth"
    "../trained_models/aad__rawnet3_fold_-1__1665328006.207422/ckpt.pth",
  ]

model:
  name: "rawnet3"
  parameters: {}
  optimizer:
    lr: 0.001
    weight_decay: 0.00005  # 5e-5
    eta_min: 0.000005  # 5e-6
