data:
  adversarial_attacks:
    - PGDL2
    - PGDL2_eps15
    - PGDL2_eps20
  seed: 42
  cnn_features_setting:
    frontend_algorithm: []  # ["mfcc"] or ["lfcc"] or ["mfcc", "lfcc"]
    use_spectrogram: False

checkpoint:
  path: "../trained_models/aad__frontend_specrnet_fold_-1__1665326541.6293828/ckpt.pth"

model:
  name: "specrnet"
  parameters:
    input_channels: 1
    frontend_algorithm: ["lfcc"]
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
