data:
  seed: 42
  cnn_features_setting:
    frontend_algorithm: []  # ["mfcc"] or ["lfcc"] or ["mfcc", "lfcc"]
    use_spectrogram: False

checkpoint:
  paths: [
    "../trained_models/aad__frontend_specrnet_fold_-1__1665326541.6293828/ckpt.pth"
  ]

model:
  name: "frontend_specrnet"
  parameters:
    input_channels: 1
    frontend_algorithm: ["lfcc"]
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
