data:
  seed: 42
  cnn_features_setting:
    frontend_algorithm: []  # ["mfcc"] or ["lfcc"] or ["mfcc", "lfcc"] or []
    use_spectrogram: False

checkpoint:
  # This part is used only in evaluation (each checkpoint is used in eval on corresponding fold).
  # To ensure reliable results make sure that the order of checkpoints is correct (i.e. fold_0, fold_1, fold_2)
  paths: []

model:
  name: "frontend_lcnn"
  parameters:
    frontend_algorithm: ["lfcc"]
    input_channels: 1
  optimizer:
    lr: 0.0001

logging:
 log_metrics: True
 existing_experiment_id: ""  # specify if you want to continue certain neptune experiment
 name: "LCNN - training, 10 epochs"
 description: ""
 tags: ["no_fold"]