data:
  seed: 42
  cnn_features_setting:
    frontend_algorithm: ["lfcc"]  # ["mfcc"] or ["lfcc"] or ["mfcc", "lfcc"]
    use_spectrogram: False

checkpoint:
  paths: []

model:
  name: "lcnn"
  parameters:
    input_channels: 1
  optimizer:
    lr: 0.0001

logging:
  log_metrics: True
  existing_experiment_id: ""  # specify if you want to continue certain neptune experiment
  name: "LCNN training"
  description: ""
  tags: []