data:
  seed: 42
  cnn_features_setting:
    frontend_algorithm: []  # ["mfcc"] or ["lfcc"] or ["mfcc", "lfcc"]
    use_spectrogram: False

checkpoint:
  paths: []

model:
  name: "rawnet3"
  parameters: {}
  optimizer:
    lr: 0.001
    weight_decay: 0.00005  # 5e-5
    # eta_min: 0.000005  # 5e-6

logging:
  log_metrics: True
  existing_experiment_id: ""  # specify if you want to continue certain neptune experiment
  name: "RawNet3 - training, 10 epochs"
  description: ""
  tags: ["no_fold"]
