data:
  seed: 42
  cnn_features_setting:
    frontend_algorithm: ["mfcc"]  # ["mfcc"] or ["lfcc"] or ["mfcc", "lfcc"]
    use_spectrogram: False

checkpoint:
  paths: []

model:
  name: "xception"
  parameters:
    input_channels: 1
  optimizer: # rawnet params
    lr: 0.00001

logging:
  log_metrics: True
  existing_experiment_id: ""  # specify if you want to continue certain neptune experiment
  name: "XceptionNet training"
  description: ""
  tags: []